# Generated by Django 4.0.4 on 2022-05-25 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail_url',
            field=models.URLField(max_length=600),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='url',
            field=models.URLField(max_length=600),
        ),
    ]
